### ISSUE TITLE
Error `Provider is required` when not passing providers to `planExecution`

### ISSUE THREAD

**Issue by jfschwarz** [gnosisguild/ser-kit#12]
When calling `planExecution()` with a simple `EOA -owns-> Safe` route and not specifying any of the optional (!!) options, it throws an error `Provider is required`.

It should use our `defaultRpc` in that case.

___

On a related note: When specifying an RPC endpoint (string) via the providers option, it fails with `provider.request is not a function`

<img width="595" alt="image" src="https://github.com/user-attachments/assets/eaa6ba26-ff82-4d39-96ac-9bd34d15bacf" />

Let's please avoid dangerous type casts like that!!!

**Comment by frontendphil** [comment]
That's a lot of exclamation points :) but I agree that these kinds of type casts are really dangerous.

**Comment by cristovaoth** [comment]
Yeah, this was a TODO I was aware of, but it slipped into the release. Fixing it now.

**Comment by cristovaoth** [comment]
> That's a lot of exclamation points :) but I agree that these kinds of type casts are really dangerous.
Agree, he could have stayed with the double "!" instead of the triple "!"

**Comment by cristovaoth** [comment]
> That's a lot of exclamation points :) but I agree that these kinds of type casts are really dangerous.

Agree, he could have stayed with the double "!" instead of the triple "!"
